### ISSUE TITLE
Autoware for F1Tenth Racing

### ISSUE THREAD

**Issue by saahu27** [AutoDRIVE-Ecosystem/AutoDRIVE-F1TENTH-Sim-Racing#3]
I want to utilize the auto ware stack with the auto drive simulator and auto drive devkit. Is there any support for this? Eventually i want to train the simulated digital twin of f1 tenth with a Reinfocement learning framework, for this is there any resources on how i go about that?

Also, i observed that all the sensors simulated are standardized does this mean, there is no noise in the measurement of sensors and i can drop out any filtering? and i can always utilize f1tenth TF frame to localize myself wrt the map frame?

**Comment by Tinker-Twins** [comment]
### AutoDRIVE Simulator Supports Autoware Stack

You can very well use AutoDRIVE Simulator with the Autoware stack. Here are a few resources that can help you get started:
- [Research Paper](https://arxiv.org/abs/2402.12670)
- [Technical Report](https://arxiv.org/abs/2402.14739)
- [GitHub Repository](https://github.com/Tinker-Twins/AutoDRIVE-Autoware)
- [Overall Documentation](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware)
- [Documentation for F1TENTH](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/blob/main/autodrive_autoware/vehicles/f1tenth/readme.md)
- [Autoware GitHub Branch](https://github.com/autowarefoundation/autoware.universe/tree/autodrive_ecosystem)
- [YouTube Playlist](https://www.youtube.com/playlist?list=PL5Hd4DIMOmEJgpsPYCoLBGNb_91PZVxgA)
- [Video Tutorial for Installation](https://youtu.be/zjYLUNiktGs?feature=shared)
- [Video Tutorial for F1TENTH](https://youtu.be/FsbARE8vwXI?feature=shared)

It is to be noted however that using the Autoware stack for the **F1TENTH Sim Racing League** is **NOT** permitted at this time (please feel free to explore, use and contribute otherwise - like for your research). In order to keep the competition framework standardized for all, we have released a [Docker image](https://hub.docker.com/r/autodriveecosystem/autodrive_f1tenth_api) of AutoDRIVE Devkit with ROS 2 API, which will **ONLY** be permitted for the competition participants. Using anything else will result in a disqualification.

### Sensor Simulation and Usage Guidelines

Since this is an initial deployment of the **F1TENTH Sim Racing League**, in order to keep things simple for the participants, we have currently not injected any noise in the sensor measurements. However, this may change in future competitions.

It is to be noted that using directly available data (e.g. `f1tenth_1` TF frame or `/autodrive/f1tenth_1/ips` topic) for localizing the vehicle for the **F1TENTH Sim Racing League** is **NOT** permitted. This data can be used for analysis but any team(s) subscribing to these topics for autonomous racing will be disqualified. It is expected that each team will work to write their own **_perception &#8594; planning &#8594; control_** algorithms based on raw sensor data (e.g. `/autodrive/f1tenth_1/lidar`, `/autodrive/f1tenth_1/front_camera`, `/autodrive/f1tenth_1/imu`, `/autodrive/f1tenth_1/left_encoder` or `/autodrive/f1tenth_1/right_encoder` topics) in order to race autonomously.

### Further Details Available Soon

The competition framework ([AutoDRIVE Simulator](https://hub.docker.com/r/autodriveecosystem/autodrive_f1tenth_sim) and [AutoDRIVE Devkit](https://hub.docker.com/r/autodriveecosystem/autodrive_f1tenth_api)) is released ahead of time for the prospective participants to get familiar with it. We will soon be releasing the competition rules, regulations and technical documentation as well. Furthermore, we will be hosting online orientation sessions to help clarify these things better.

Hope this helps and all the best!
