### ISSUE TITLE
Publishing to throttle_command doesn't move the car in the simulator

### ISSUE THREAD

**Issue by saahu27** [AutoDRIVE-Ecosystem/AutoDRIVE-F1TENTH-Sim-Racing#4]
ros2 topic pub -r 1 /autodrive/f1tenth_1/throttle_command std_msgs/msg/Float32 "{data: 1.0}"
publisher: beginning loop

publishing #1: std_msgs.msg.Float32(data=1.0)
publishing #2: std_msgs.msg.Float32(data=1.0)
publishing #3: std_msgs.msg.Float32(data=1.0)

i have the simulator connected to the ip address 172.18.0.3 on port 4567. I can see the topics in rviz image, tf etc.

root@bd5628f8f622:/home/autodrive_devkit# ros2 node list
/autodrive_incoming_bridge
/autodrive_outgoing_bridge
/rviz
/transform_listener_impl_6510906eb600
 
ros2 node info : 
 /autodrive_outgoing_bridge 
/autodrive_outgoing_bridge
  Subscribers:
    /autodrive/f1tenth_1/steering_command: std_msgs/msg/Float32
    /autodrive/f1tenth_1/throttle_command: std_msgs/msg/Float32
  Publishers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /rosout: rcl_interfaces/msg/Log
  Service Servers:
    /autodrive_outgoing_bridge/describe_parameters: rcl_interfaces/srv/DescribeParameters
    /autodrive_outgoing_bridge/get_parameter_types: rcl_interfaces/srv/GetParameterTypes
    /autodrive_outgoing_bridge/get_parameters: rcl_interfaces/srv/GetParameters
    /autodrive_outgoing_bridge/list_parameters: rcl_interfaces/srv/ListParameters
    /autodrive_outgoing_bridge/set_parameters: rcl_interfaces/srv/SetParameters
    /autodrive_outgoing_bridge/set_parameters_atomically: rcl_interfaces/srv/SetParametersAtomically
  Service Clients:

  Action Servers:

  Action Clients:

But when i publish a command, the simulator shows no effect. Can anyone please explain why?

**Comment by Tinker-Twins** [comment]
@saahu27 Based on the logs you have shared (very helpful by the way), it does not seem that there is any error or issue.

One of the most important thing to check would be in which mode you are running the vehicle - `Manual` or `Autonomous`. In order to switch modes, click on the `Mode` button to change its status from `Manual` to `Autonomous` and you should be good to go!

Here is a screenshot to guide you better:
![Driving Mode](https://github.com/user-attachments/assets/98f80a0b-6212-465c-bf55-a08a58cc9324)

Hope this helps and all the best!
